### ISSUE TITLE
Incorrect Calculation

### ISSUE THREAD

**Issue by pepebecker** [derhuerst/js-playgrounds#2]
If you for example enter `+('0' + 1)` you will get `101` whereas you should get `1`.

**Comment by derhuerst** [comment]
will try to fix it tonight at the ok lab.

**Comment by derhuerst** [comment]
`node -e 'console.log(+("0" + 1)')`

**Comment by derhuerst** [comment]
In fact it is only a bug of _presentation_, not of executing JS properly. There is two values being shown next to the line (`'01'` and `1`). Because both overlap each other, it looks as if the calculation is wrong.

Will fix the overlapping issue tonight.
